/* !!
 * Code generated by fkit
 * If you need to write additional functions, should create a separate file.
 * File Created: Sunday, 27 April 2025 15:51:44 +07:00
 * Author: VietLD (leduyviet2612@gmail.com)
 * -----
 * Last Modified: Sunday, 27 April 2025 15:51:44 +07:00
 * Modified By: HIEUBV\hieubv
 * -----
 * Copyright 2025. All rights reserved.
 */

package postgres_dao

import (
	"fmt"
	"strings"

	sq "github.com/Masterminds/squirrel"

	"github.com/bachhieu/fountain/baselib/sql_client"
	"github.com/bachhieu/fountain/baselib/v_log"
	"github.com/bachhieu/test/biz/dal/do/cate_do"
	"github.com/bachhieu/test/biz/dal/models"
	"github.com/jmoiron/sqlx"
)

var (
	cates_table  = "cates"
	cates_fields = []string{
		"id", "name", "description", "created_by", "created_time", "updated_time",
	}
)

func catesToMap(record *models.CateMD) map[string]interface{} {
	return map[string]interface{}{
		"id":           record.ID,
		"name":         record.Name,
		"description":  record.Description,
		"created_by":   record.CreatedBy,
		"created_time": record.CreatedTime,
		"updated_time": record.UpdatedTime,
	}
}

type CatesDAO struct {
	*sqlx.DB
}

func NewCatesDAO(DB *sqlx.DB) *CatesDAO {
	return &CatesDAO{DB}
}

func (dao *CatesDAO) Insert(record *models.CateMD, opts ...Option) error {
	builder := sq.Insert(cates_table).SetMap(catesToMap(record))

	sqlQuery, args, err := builder.PlaceholderFormat(sq.Dollar).ToSql()
	if err != nil {
		v_log.V(1).WithError(err).Errorf("CatesDAO::Insert - Lỗi xây dựng truy vấn: %+v", err)
		return err
	}

	_, err = ExecWithTx(dao.DB, opts, sqlQuery, args...)
	if err != nil {
		v_log.V(1).WithError(err).Errorf("CatesDAO::Insert - Lỗi thực thi truy vấn: %+v", err)
		return err
	}

	return nil
}

func (dao *CatesDAO) BatchInsert(records []*models.CateMD, opts ...Option) error {
	builder := sq.Insert(cates_table).
		Columns(cates_fields...)
	for _, record := range records {
		builder = builder.SetMap(catesToMap(record))
	}

	sqlQuery, args, err := builder.PlaceholderFormat(sq.Dollar).ToSql()
	if err != nil {
		v_log.V(1).WithError(err).Errorf("CatesDAO::BatchInsert - Lỗi xây dựng truy vấn: %+v", err)
		return err
	}

	if _, err := ExecWithTx(dao.DB, opts, sqlQuery, args...); err != nil {
		v_log.V(1).WithError(err).Errorf("CatesDAO::BatchInsert - Lỗi thực thi truy vấn: %+v", err)
		return err
	}

	return nil
}

func (dao *CatesDAO) BatchUpsert(records []*models.CateMD, opts ...Option) error {
	builder := sq.Insert(cates_table).
		Columns(cates_fields...)

	for _, record := range records {
		builder = builder.Values(
			record.ID,
			record.Name,
			record.Description,
			record.CreatedBy,
			record.CreatedTime,
			record.UpdatedTime,
		)
	}

	//TODO: Sửa lại ON CONFLICT sẽ dựa trên các trường cần thiết
	builder = builder.Suffix(`ON CONFLICT (id) DO UPDATE SET
		name = EXCLUDED.name,
		description = EXCLUDED.description,
		created_by = EXCLUDED.created_by,
		created_time = EXCLUDED.created_time,
		updated_time = EXCLUDED.updated_time`)

	sqlQuery, args, err := builder.PlaceholderFormat(sq.Dollar).ToSql()
	if err != nil {
		v_log.V(1).WithError(err).Errorf("CatesDAO::BatchUpsert - Lỗi xây dựng truy vấn: %+v", err)
		return err
	}

	if _, err := ExecWithTx(dao.DB, opts, sqlQuery, args...); err != nil {
		v_log.V(1).WithError(err).Errorf("CatesDAO::BatchUpsert - Lỗi thực thi truy vấn: %+v", err)
		return err
	}

	return nil
}

func (dao *CatesDAO) Upsert(record *models.CateMD, opts ...Option) error {
	builder := sq.Insert(cates_table).SetMap(catesToMap(record)).
		Suffix(`ON CONFLICT (id) DO UPDATE SET
		name = EXCLUDED.name,
		description = EXCLUDED.description,
		created_by = EXCLUDED.created_by,
		created_time = EXCLUDED.created_time,
		updated_time = EXCLUDED.updated_time`)

	sqlQuery, args, err := builder.PlaceholderFormat(sq.Dollar).ToSql()
	if err != nil {
		v_log.V(1).WithError(err).Errorf("CatesDAO::Upsert - Lỗi xây dựng truy vấn: %+v", err)
		return err
	}

	_, err = ExecWithTx(dao.DB, opts, sqlQuery, args...)
	if err != nil {
		v_log.V(1).WithError(err).Errorf("CatesDAO::Upsert - Lỗi thực thi truy vấn: %+v", err)
		return err
	}

	return nil
}

func (dao *CatesDAO) Get(id string, opts ...Option) *models.CateMD {
	queryBuilder := sq.Select(cates_fields...).
		From(cates_table).
		Where(sq.Eq{"id": id})

	query, args, err := queryBuilder.PlaceholderFormat(sq.Dollar).ToSql()
	if err != nil {
		v_log.V(1).WithError(err).Errorf("CatesDAO::Get - Lỗi xây dựng truy vấn: %+v", err)
		return nil
	}

	do, err := sql_client.QueryDataParser[models.CateMD](dao.DB, query, nil, args...)
	if err != nil {
		v_log.V(1).WithError(err).Errorf("CatesDAO::Get - Lỗi thực thi truy vấn: %+v", err)
		return nil
	}

	return do
}

func (dao *CatesDAO) GetMany(ids []string, opts ...Option) ([]*models.CateMD, error) {
	queryBuilder := sq.Select(cates_fields...).
		From(cates_table).
		Where(sq.Eq{"id": ids})

	query, args, err := queryBuilder.PlaceholderFormat(sq.Dollar).ToSql()
	if err != nil {
		v_log.V(1).WithError(err).Errorf("CatesDAO::GetMany - Error building query: %+v", err)
		return nil, err
	}

	res, err := sql_client.QueryListDataParser[models.CateMD](dao.DB, query, nil, args...)
	if err != nil {
		v_log.V(1).WithError(err).Errorf("CatesDAO::GetMany - Error executing query: %+v", err)
		return nil, err
	}

	return res, nil
}

func (dao *CatesDAO) GetAll(opts ...Option) []*models.CateMD {
	queryBuilder := sq.Select(cates_fields...).
		From(cates_table).
		OrderBy("created_time ASC")

	query, args, err := queryBuilder.PlaceholderFormat(sq.Dollar).ToSql()
	if err != nil {
		v_log.V(1).WithError(err).Errorf("CatesDAO::GetAll - Lỗi xây dựng truy vấn: %+v", err)
		return nil
	}

	res, err := sql_client.QueryListDataParser[models.CateMD](dao.DB, query, nil, args...)
	if err != nil {
		v_log.V(1).WithError(err).Errorf("CatesDAO::GetAll - Lỗi thực thi truy vấn: %+v", err)
		return nil
	}

	return res
}

func (dao *CatesDAO) Gets(params *cate_do.CateQueryParams, offset, limit int, opts ...Option) ([]*models.CateMD, error) {
	queryBuilder := sq.Select(cates_fields...).
		From(cates_table)

	if params.Q != nil && *params.Q != "" {
		queryBuilder = queryBuilder.Where("LOWER(name) LIKE ?", "%"+strings.ToLower(*params.Q)+"%")
	}

	queryBuilder = queryBuilder.
		OrderBy("created_time ASC").
		Offset(uint64(offset)).
		Limit(uint64(limit))

	query, args, err := queryBuilder.PlaceholderFormat(sq.Dollar).ToSql()
	if err != nil {
		v_log.V(1).WithError(err).Errorf("CatesDAO::Gets - Error building query: %+v", err)
		return nil, err
	}

	res, err := sql_client.QueryListDataParser[models.CateMD](dao.DB, query, nil, args...)
	return res, err
}

func (dao *CatesDAO) Update(md *models.CateMD, opts ...Option) error {
	fmt.Println("------::", md)

	queryBuilder := sq.Update(cates_table).
		SetMap(catesToMap(md)).
		Where(sq.Eq{"id": md.ID})

	sqlQuery, args, err := queryBuilder.PlaceholderFormat(sq.Dollar).ToSql()
	if err != nil {
		v_log.V(1).WithError(err).Errorf("CatesDAO::Update - Lỗi xây dựng truy vấn: %+v", err)
		return err
	}

	_, err = ExecWithTx(dao.DB, opts, sqlQuery, args...)
	if err != nil {
		v_log.V(1).WithError(err).Errorf("CatesDAO::Update - Lỗi thực thi truy vấn: %+v", err)
		return err
	}

	return nil
}
func (dao *CatesDAO) Delete(id string, opts ...Option) error {
	builder := sq.Delete(cates_table).
		Where(sq.Eq{"id": id})

	query, args, err := builder.PlaceholderFormat(sq.Dollar).ToSql()
	if err != nil {
		v_log.V(1).WithError(err).Errorf("CatesDAO::Delete - Lỗi xây dựng truy vấn: %+v", err)
		return err
	}

	_, err = ExecWithTx(dao.DB, opts, query, args...)
	if err != nil {
		v_log.V(1).WithError(err).Errorf("CatesDAO::Delete - Lỗi thực thi truy vấn: %+v", err)
		return err
	}

	return nil
}

func (dao *CatesDAO) CountTotal(params *cate_do.CateQueryParams, opts ...Option) int {
	queryBuilder := sq.Select("COUNT(1)").
		From(cates_table)

	if params.Q != nil && *params.Q != "" {
		queryBuilder = queryBuilder.Where("LOWER(name) LIKE ?", "%"+strings.ToLower(*params.Q)+"%")
	}

	query, args, err := queryBuilder.PlaceholderFormat(sq.Dollar).ToSql()
	if err != nil {
		v_log.V(1).WithError(err).Errorf("CatesDAO::CountTotal - Error building query: %+v", err)
		return 0
	}

	var count int
	err = dao.DB.QueryRow(query, args...).Scan(&count)
	if err != nil {
		v_log.V(1).WithError(err).Errorf("CatesDAO::CountTotal - Error executing query: %+v", err)
		return 0
	}

	return count
}
