/* !!
 * Code generated by fkit
 * If you need to write additional functions, should create a separate file.
 * File Created: Sunday, 27 April 2025 15:51:44 +07:00
 * Author: VietLD (leduyviet2612@gmail.com)
 * -----
 * Last Modified: Sunday, 27 April 2025 15:51:44 +07:00
 * Modified By: HIEUBV\hieubv
 * -----
 * Copyright 2025. All rights reserved.
 */

package cates

import (
	"github.com/bachhieu/fountain/baselib/v_log"
	f_core "github.com/bachhieu/fountain/biz/f_core"
	"github.com/bachhieu/test/biz/dal/dao"
	"github.com/bachhieu/test/biz/dal/dao/postgres_dao"
	"github.com/bachhieu/test/biz/dal/dao/redis_dao"
)

type cateDAO struct {
	catesDAO   *postgres_dao.CatesDAO
	catesCache *redis_dao.CatesCache
}

type CatesController struct {
	dao *cateDAO
}

func (ctrl *CatesController) InstallController() {
	ctrl.dao.catesDAO = dao.GetCatesDAO(dao.TEST_DB_MASTER)
	ctrl.dao.catesCache = dao.GetCatesCache(dao.TEST_CACHE)
}

func (ctrl *CatesController) RegisterCallback(cb interface{}) {
}

func (ctrl *CatesController) AfterInstalledDone() {
	v_log.V(3).Infof("CatesController::AfterInstalledDone")
}

func init() {
	f_core.RegisterCoreController(&CatesController{dao: &cateDAO{}})
}
