/* !!
 * Code generated by fkit
 * If you need to write additional functions, should create a separate file.
 * File Created: Sunday, 27 April 2025 16:48:24 +07:00
 * Author: VietLD (leduyviet2612@gmail.com)
 * -----
 * Last Modified: Sunday, 27 April 2025 16:48:24 +07:00
 * Modified By: HIEUBV\hieubv
 * -----
 * Copyright 2025. All rights reserved.
 */

package reviews

import (
	"github.com/bachhieu/fountain/baselib/v_net/v_api"
	"github.com/bachhieu/fountain/biz/f_core"
	"github.com/bachhieu/test/biz/core/reviews"
)

type ReviewsAPI struct {
	*v_api.VolioAPI
	reviewsController *reviews.ReviewsController
}

func NewReviewsAPI(controllers []f_core.CoreController) *ReviewsAPI {
	impl := &ReviewsAPI{VolioAPI: v_api.GetVolioAPIInstance()}

	for _, ctrl := range controllers {
		switch x := ctrl.(type) {
		case *reviews.ReviewsController:
			impl.reviewsController = x
		}
	}

	return impl
}
