version: '3.9'

services:
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: test
      POSTGRES_PASSWORD: postgres
