
services:
  app:
    image: bachviethieu/hieubv-reco:testing
    container_name: demo
    environment:
      - CONTAINER_ROLE=main
    build:
          context: .
          dockerfile: Dockerfile.base  # nếu bạn build từ Dockerfile.base
    ports:
      - "3000:3000"
    volumes:
      - ./config.json:/app/config.json  # mount file config.json vào trong container
    working_dir: /app
    restart: unless-stopped
