
services:
  app:
    image: bachviethieu/demo
    container_name: demo
    environment:
      - CONTAINER_ROLE=main
    ports:
      - "3000:3000"
    volumes:
      - ./config.json:/app/config.json  # mount file config.json vào trong container
    working_dir: /app
    restart: unless-stopped
