/* !!
 * Code generated by fkit
 * If you need to write additional functions, should create a separate file.
 * File Created: Sunday, 27 April 2025 14:19:49 +07:00
 * Author: VietLD (leduyviet2612@gmail.com)
 * -----
 * Last Modified: Sunday, 27 April 2025 14:19:49 +07:00
 * Modified By: HIEUBV\hieubv
 * -----
 * Copyright 2025. All rights reserved.
 */

package main

import (
	// Make fountain initialize first
	// _ "github.com/bachhieu/kit"

	"github.com/bachhieu/fountain"

	// New line
	"github.com/bachhieu/test/server"
)

// @title Test API
// @version 3.0
// @description Tài liệu kết nối Test API
// @termsOfService empty
// @contact.name admin
// @contact.email admin@volio.vn
// @license.name GNU 3.0
// @license.url https://www.gnu.org/licenses/gpl-3.0.en.html
// @Server http://localhost:3000/api/v1/ local
// @securityDefinitions.bearerAuth  bearer
// @BasePath /api/v1
func main() {
	instance := server.NewTestServer()
	fountain.DoMainAppInstance(instance)
}
