/* !!
 * Code generated by fkit
 * If you need to write additional functions, should create a separate file.
 * File Created: Sunday, 27 April 2025 16:10:50 +07:00
 * Author: VietLD (leduyviet2612@gmail.com)
 * -----
 * Last Modified: Sunday, 27 April 2025 16:10:50 +07:00
 * Modified By: HIEUBV\hieubv
 * -----
 * Copyright 2025. All rights reserved.
 */

package products

import (
	"github.com/bachhieu/fountain/baselib/v_log"
	f_core "github.com/bachhieu/fountain/biz/f_core"
	"github.com/bachhieu/test/biz/dal/dao"
	"github.com/bachhieu/test/biz/dal/dao/postgres_dao"
	"github.com/bachhieu/test/biz/dal/dao/redis_dao"
)

type productDAO struct {
	productsDAO   *postgres_dao.ProductsDAO
	productsCache *redis_dao.ProductsCache
}

type ProductsController struct {
	dao *productDAO
}

func (ctrl *ProductsController) InstallController() {
	ctrl.dao.productsDAO = dao.GetProductsDAO(dao.TEST_DB_MASTER)
	ctrl.dao.productsCache = dao.GetProductsCache(dao.TEST_CACHE)
}

func (ctrl *ProductsController) RegisterCallback(cb interface{}) {
}

func (ctrl *ProductsController) AfterInstalledDone() {
	v_log.V(3).Infof("ProductsController::AfterInstalledDone")
}

func init() {
	f_core.RegisterCoreController(&ProductsController{dao: &productDAO{}})
}
