/* !!
 * Code generated by fkit
 * If you need to write additional functions, should create a separate file.
 * File Created: Sunday, 27 April 2025 14:28:41 +07:00
 * Author: VietLD (leduyviet2612@gmail.com)
 * -----
 * Last Modified: Sunday, 27 April 2025 14:28:41 +07:00
 * Modified By: HIEUBV\hieubv
 * -----
 * Copyright 2025. All rights reserved.
 */

package user_do

import (
	"github.com/bachhieu/fountain/baselib/v_log"
	"github.com/bachhieu/fountain/baselib/v_net/v_api"
	"github.com/bachhieu/fountain/proto/v_proto"
	"github.com/bachhieu/test/biz/dal/models"
	"github.com/bachhieu/test/pkg/constant"
)

// enable custom message validate if needed
// var _ validator.ICustomMessage = (*UpdateUserReq)(nil)

type UpdateUserReq struct {
	ID           string                `json:""`
	Username     string                `json:"username" validate:"omitempty,min=1,max=255" example:"carroll.myrtle"`
	Email        string                `json:"email" validate:"omitempty,min=1,max=255" example:"leannon.herminia@bxt.com"`
	PasswordHash string                `json:"password_hash" validate:"omitempty,min=1,max=255" example:"9HZdzEr.uWct"`
	FullName     string                `json:"full_name" validate:"omitempty,min=1,max=255" example:"Mr. Cortez Nicolas II"`
	Role         string                `json:"-"`
	Provider     constant.ProviderUser `json:"-"`
}

func (d *UpdateUserReq) Validated() (*models.UserMD, *v_proto.VolioRpcError) {
	if err := v_api.Validate(d); err != nil {
		v_log.V(1).WithError(err).Errorf("UpdateUserReq::Validated - Error: %+v", err)
		return nil, v_proto.NewRpcError(int32(v_proto.VolioRpcErrorCodes_BAD_REQUEST), err.Error())
	}

	model := &models.UserMD{
		ID:           d.ID,
		Username:     d.Username,
		Email:        d.Email,
		PasswordHash: d.PasswordHash,
		FullName:     d.FullName,
		Role:         d.Role,
		Provider:     d.Provider,
	}

	return model, nil
}
