/* !!
 * Code generated by fkit
 * If you need to write additional functions, should create a separate file.
 * File Created: Sunday, 27 April 2025 14:19:49 +07:00
 * Author: VietLD (leduyviet2612@gmail.com)
 * -----
 * Last Modified: Sunday, 27 April 2025 14:19:49 +07:00
 * Modified By: HIEUBV\hieubv
 * -----
 * Copyright 2025. All rights reserved.
 */

package server

import (
	_ "github.com/bachhieu/test/docs"
	"github.com/gofiber/fiber/v2"
	swagger "github.com/swaggo/fiber-swagger"

	// volior_client "github.com/bachhieu/volior/client"

	"github.com/bachhieu/fountain/baselib/v_net/v_api"
)

func (s *TestServer) initRouter() {
	prefix := "/api/v1"
	apiGr := s.ApiServer.Group(prefix)

	apiPrivateGr := s.ApiServer.Group("/private" + prefix)
	_ = apiPrivateGr
	// if env.Environment != "local" {
	// 	apiGr.Use(s.authController.JwtGateway)
	// }

	/* Swagger */
	adminGr := apiGr.Group("/admin")
	adminGr.Static("/api-docs", "./docs")
	adminGr.Get("/api-docs/*", swagger.FiberWrapHandler(func(c *swagger.Config) {
		c.URL = "swagger.json"
	}))

	// if env.Environment == "local" {
	// 	apiGr.Use(localMiddleGate)
	// 	apiPrivateGr.Use(localMiddleGate)
	// }

	/* Admin route */

	{
		productsGr := adminGr.Group("/products", s.usersHandler.RequiredLogin)
		productsGr.Post("/", s.productsHandler.Create)
		productsGr.Get("/pagination", s.productsHandler.GetPagination)
		productsGr.Get("/detail", s.productsHandler.Get)
		productsGr.Put("/", s.productsHandler.Update)
		productsGr.Delete("/", s.productsHandler.Delete)
	}

	{
		catesGr := adminGr.Group("/cates", s.usersHandler.RequiredLogin)
		catesGr.Post("/", s.catesHandler.Create)
		catesGr.Get("/pagination", s.catesHandler.GetPagination)
		catesGr.Get("/detail", s.catesHandler.Get)
		catesGr.Put("/", s.catesHandler.Update)
		catesGr.Delete("/", s.catesHandler.Delete)
	}

	{
		usersGr := adminGr.Group("/users")
		// if env.Environment != "local" {
		// 	usersGr.Use(volior_client.GetVoliorClient().JwtGateway)
		// }
		usersGr.Post("/sign-up", s.usersHandler.SignUp)
		usersGr.Post("/sign-in", s.usersHandler.SignIn)
		usersGr.Get("/pagination/", s.usersHandler.RequiredLogin, s.usersHandler.GetPagination)
		usersGr.Get("/detail", s.usersHandler.RequiredLogin, s.usersHandler.Get)
		usersGr.Put("/", s.usersHandler.RequiredLogin, s.usersHandler.Update)
		usersGr.Delete("/", s.usersHandler.RequiredLogin, s.usersHandler.Delete)
	}

}

func localMiddleGate(c *fiber.Ctx) (err error) {
	c.Locals(v_api.KContextKeyUserID, "00000000-0000-0000-0000-000000000000")
	c.Locals(v_api.KContextKeyUserName, "admin")

	return c.Next()
}
