/* !!
 * Code generated by fkit
 * If you need to write additional functions, should create a separate file.
 * File Created: Sunday, 27 April 2025 14:19:49 +07:00
 * Author: VietLD (leduyviet2612@gmail.com)
 * -----
 * Last Modified: Sunday, 27 April 2025 14:19:49 +07:00
 * Modified By: HIEUBV\hieubv
 * -----
 * Copyright 2025. All rights reserved.
 */

package server

import (
	"time"

	"github.com/bachhieu/fountain/baselib/sql_client"
	"github.com/bachhieu/test/biz/dal/dao"
)

// DO NOT EDIT IT, ONLY ADDING MORE
func init() {
	timeNow := int32(time.Now().Unix())
	sql_client.InitVersionMigrate(dao.TEST_DB_MASTER)

	sql_client.AddVersionMigrateQuery(dao.TEST_DB_MASTER, &sql_client.VersionMD{
		Name:        "",
		Query:       ``,
		CreatedTime: timeNow,
	})

	sql_client.AddVersionMigrateQuery(dao.TEST_DB_MASTER, &sql_client.VersionMD{
		Name: sql_client.MigrateCreateTableKey("users"),
		Query: `
		CREATE TABLE IF NOT EXISTS users (
			id VARCHAR(36) PRIMARY KEY,
			username VARCHAR(255) DEFAULT '',
			email varchar(50) NOT NULL UNIQUE,
			password_hash VARCHAR(255) DEFAULT '',
			full_name VARCHAR(255) DEFAULT '',
			role VARCHAR(255) DEFAULT 'user',
			provider VARCHAR(255) DEFAULT 'internal',
			created_time INT DEFAULT EXTRACT(EPOCH FROM NOW()),
			updated_time INT DEFAULT EXTRACT(EPOCH FROM NOW()),
			deleted_time INT DEFAULT 0
		)`,
		CreatedTime: timeNow,
	})

	sql_client.AddVersionMigrateQuery(dao.TEST_DB_MASTER, &sql_client.VersionMD{
		Name: sql_client.MigrateCreateTableKey("cates"),
		Query: `
		CREATE TABLE IF NOT EXISTS cates (
			id VARCHAR(36) PRIMARY KEY,
			name VARCHAR(255) DEFAULT '',
			description TEXT DEFAULT '',
			created_by VARCHAR(36) NOT NULL REFERENCES users(id),
			created_time INT DEFAULT EXTRACT(EPOCH FROM NOW()),
			updated_time INT DEFAULT EXTRACT(EPOCH FROM NOW()),
			deleted_time INT DEFAULT 0
		)`,
		CreatedTime: timeNow,
	})

	sql_client.AddVersionMigrateQuery(dao.TEST_DB_MASTER, &sql_client.VersionMD{
		Name: sql_client.MigrateCreateTableKey("products"),
		Query: `
		CREATE TABLE IF NOT EXISTS products (
			id VARCHAR(36) PRIMARY KEY,
			name VARCHAR(255) DEFAULT '',
			description TEXT DEFAULT '',
			price DECIMAL(10,2) DEFAULT 0,
			stock_quantity INT DEFAULT 0,
			display BOOLEAN DEFAULT TRUE,
			created_by VARCHAR(36) NOT NULL REFERENCES users(id),
			created_time INT DEFAULT EXTRACT(EPOCH FROM NOW()),
			updated_time INT DEFAULT EXTRACT(EPOCH FROM NOW()),
			deleted_time INT DEFAULT 0
		)`,
		CreatedTime: timeNow,
	})
}
