/* !!
 * Code generated by fkit
 * If you need to write additional functions, should create a separate file.
 * File Created: Sunday, 27 April 2025 14:28:41 +07:00
 * Author: VietLD (leduyviet2612@gmail.com)
 * -----
 * Last Modified: Sunday, 27 April 2025 14:28:41 +07:00
 * Modified By: HIEUBV\hieubv
 * -----
 * Copyright 2025. All rights reserved.
 */

package users

import (
	"github.com/bachhieu/fountain/baselib/v_log"
	f_core "github.com/bachhieu/fountain/biz/f_core"
	"github.com/bachhieu/test/biz/dal/dao"
	"github.com/bachhieu/test/biz/dal/dao/postgres_dao"
	"github.com/bachhieu/test/biz/dal/dao/redis_dao"
)

type userDAO struct {
	usersDAO   *postgres_dao.UsersDAO
	usersCache *redis_dao.UsersCache
}

type UsersController struct {
	dao *userDAO
}

func (ctrl *UsersController) InstallController() {
	ctrl.dao.usersDAO = dao.GetUsersDAO(dao.TEST_DB_MASTER)
	ctrl.dao.usersCache = dao.GetUsersCache(dao.TEST_CACHE)
}

func (ctrl *UsersController) RegisterCallback(cb interface{}) {
}

func (ctrl *UsersController) AfterInstalledDone() {
	v_log.V(3).Infof("UsersController::AfterInstalledDone")
}

func init() {
	f_core.RegisterCoreController(&UsersController{dao: &userDAO{}})
}
