/* !!
 * Code generated by fkit
 * If you need to write additional functions, should create a separate file.
 * File Created: Sunday, 27 April 2025 14:28:41 +07:00
 * Author: VietLD (leduyviet2612@gmail.com)
 * -----
 * Last Modified: Sunday, 27 April 2025 14:28:41 +07:00
 * Modified By: HIEUBV\hieubv
 * -----
 * Copyright 2025. All rights reserved.
 */

package users

import (
	"github.com/bachhieu/fountain/baselib/v_log"
	"github.com/bachhieu/fountain/proto/v_proto"
	"github.com/bachhieu/test/biz/core"
	"github.com/bachhieu/test/biz/dal/do/user_do"
	"github.com/bachhieu/test/biz/dal/models"
)

var _ core.UsersCallback = &UsersController{}

func (ctrl *UsersController) Get(id string) *models.UserMD {
	// Try get from cache first
	if data := ctrl.dao.usersCache.Get(id); data != nil {
		return data
	}

	// Get from dao
	md := ctrl.dao.usersDAO.Get(id)
	if md == nil {
		return nil
	}

	// Save to cache
	go func() {
		if err := ctrl.dao.usersCache.Save(md); err != nil {
			v_log.V(1).WithError(err).Errorf("UsersController::Get - Cache Error: %+v", err)
		}
	}()

	return md
}

func (ctrl *UsersController) Gets(params *user_do.UserQueryParams, offset, limit int) ([]*models.UserMD, *v_proto.VolioRpcError) {
	res, err := ctrl.dao.usersDAO.Gets(params, offset, limit)
	if err != nil {
		v_log.V(1).WithError(err).Errorf("UsersController::Gets - Error: %+v", err)
		return nil, v_proto.NewRpcError(int32(v_proto.VolioRpcErrorCodes_BAD_REQUEST), "some thing went wrong")
	}

	return res, nil
}

func (ctrl *UsersController) CountTotal(params *user_do.UserQueryParams) int {
	return ctrl.dao.usersDAO.CountTotal(params)
}

func (ctrl *UsersController) Create(input *user_do.CreateUserReq) (*user_do.UserResponse, *v_proto.VolioRpcError) {
	md, err := input.Validated()
	if md == nil {
		return nil, v_proto.NewRpcError(int32(v_proto.VolioRpcErrorCodes_BAD_REQUEST), "Can't create User!")
	}
	if err != nil {
		v_log.V(1).WithError(err).Errorf("UsersController::Create - Error: %+v", err)
		return nil, err
	}

	if err := ctrl.dao.usersDAO.Insert(md); err != nil {
		v_log.V(1).WithError(err).Errorf("UsersController::Create - Error: %+v", err)
		return nil, v_proto.NewRpcError(int32(v_proto.VolioRpcErrorCodes_SAVE_DATA), "failed to create")
	}
	return user_do.NewUserResponse(md), nil
}

func (ctrl *UsersController) SignIn(input *user_do.CreateUserReq) (*user_do.UserResponse, *v_proto.VolioRpcError) {

	user := ctrl.dao.usersDAO.GetByEmail(input.Email)
	if user == nil {
		return nil, v_proto.NewRpcError(int32(v_proto.VolioRpcErrorCodes_SAVE_DATA), "Wrong email or password!")
	}

	if !input.CheckPasswordHash(user.PasswordHash) {
		return nil, v_proto.NewRpcError(int32(v_proto.VolioRpcErrorCodes_SAVE_DATA), "Wrong email or password!")
	}

	return user_do.NewUserResponse(user), nil
}

func (ctrl *UsersController) Update(input *user_do.UpdateUserReq) *v_proto.VolioRpcError {
	newMd, err := input.Validated()
	if err != nil {
		v_log.V(1).WithError(err).Errorf("UsersController::Update - Error: %+v", err)
		return err
	}

	oldMd := ctrl.dao.usersDAO.Get(newMd.ID)
	if oldMd == nil {
		return v_proto.NewRpcError(int32(v_proto.VolioRpcErrorCodes_DATA_NOT_FOUND), "User not found")
	}

	if err := ctrl.dao.usersDAO.Update(oldMd.AllowedUpdateFields(newMd)); err != nil {
		v_log.V(1).WithError(err).Errorf("UsersController::Update - Error: %+v", err)
		return v_proto.NewRpcError(int32(v_proto.VolioRpcErrorCodes_SAVE_DATA), "failed to update")
	}
	// Delete cache
	if err := ctrl.dao.usersCache.Delete(newMd.ID); err != nil {
		v_log.V(1).WithError(err).Errorf("UsersController::Update - Cache Error: %+v", err)
	}
	return nil
}

func (ctrl *UsersController) Delete(id string) *v_proto.VolioRpcError {
	// Delete from cache first
	if err := ctrl.dao.usersCache.Delete(id); err != nil {
		v_log.V(1).WithError(err).Errorf("UsersController::Delete - Cache Error: %+v", err)
	}

	if err := ctrl.dao.usersDAO.Delete(id); err != nil {
		v_log.V(1).WithError(err).Errorf("UsersController::Delete - Error: %+v", err)
		return v_proto.NewRpcError(int32(v_proto.VolioRpcErrorCodes_SAVE_DATA), "failed to delete")
	}
	return nil
}
