/* !!
 * Code generated by fkit
 * If you need to write additional functions, should create a separate file.
 * File Created: Sunday, 27 April 2025 14:19:49 +07:00
 * Author: VietLD (leduyviet2612@gmail.com)
 * -----
 * Last Modified: Sunday, 27 April 2025 14:19:49 +07:00
 * Modified By: HIEUBV\hieubv
 * -----
 * Copyright 2025. All rights reserved.
 */

package core

import (
	"github.com/bachhieu/fountain/proto/v_proto"
	"github.com/bachhieu/test/biz/dal/do/cate_do"
	"github.com/bachhieu/test/biz/dal/do/product_do"
	"github.com/bachhieu/test/biz/dal/models"
)

// --------------------------------- CALLBACK -------------------------------

type UsersCallback interface {
	// Get(id string) *models.UserMD
	// Gets(params *user_do.UserQueryParams, offset, limit int) ([]*models.UserMD, *v_proto.VolioRpcError)
	// CountTotal(params *user_do.UserQueryParams) int
	// Update(input *user_do.UpdateUserReq) *v_proto.VolioRpcError
	// Delete(id string) *v_proto.VolioRpcError
}

type CatesCallback interface {
	Get(id string) *models.CateMD
	Gets(params *cate_do.CateQueryParams, offset, limit int) ([]*models.CateMD, *v_proto.VolioRpcError)
	CountTotal(params *cate_do.CateQueryParams) int
	Create(input *cate_do.CreateCateReq) *v_proto.VolioRpcError
	Update(input *cate_do.UpdateCateReq) *v_proto.VolioRpcError
	Delete(id string) *v_proto.VolioRpcError
}

type ProductsCallback interface {
	Get(id string) *models.ProductMD
	Gets(params *product_do.ProductQueryParams, offset, limit int) ([]*models.ProductMD, *v_proto.VolioRpcError)
	CountTotal(params *product_do.ProductQueryParams) int
	Create(input *product_do.CreateProductReq) *v_proto.VolioRpcError
	Update(input *product_do.UpdateProductReq) *v_proto.VolioRpcError
	Delete(id string) *v_proto.VolioRpcError
}
