/* !!
 * Code generated by fkit
 * If you need to write additional functions, should create a separate file.
 * File Created: Sunday, 27 April 2025 16:10:50 +07:00
 * Author: VietLD (leduyviet2612@gmail.com)
 * -----
 * Last Modified: Sunday, 27 April 2025 16:10:50 +07:00
 * Modified By: HIEUBV\hieubv
 * -----
 * Copyright 2025. All rights reserved.
 */

package product_do

import (
	"github.com/bachhieu/test/biz/dal/models"
)

type ProductResponse struct {
	ID            string  `json:"id" example:"01HFGRZQHPY8JHVRZ7NSRDGVB5"`
	Name          string  `json:"name" example:"Obie Schroeder"`
	Description   string  `json:"description" example:"eaque ad est et impedit."`
	Price         float64 `json:"price" example:"858"`
	StockQuantity int     `json:"stock_quantity" example:"55"`
	Display       bool    `json:"display" example:"false"`
	CreatedBy     string  `json:"created_by" example:"783"`
	CreatedTime   int32   `json:"created_time" example:"1738684701"`
	UpdatedTime   int32   `json:"updated_time" example:"1738684701"`
}

func NewProductResponse(md *models.ProductMD) *ProductResponse {
	if md == nil {
		return nil
	}

	return &ProductResponse{
		ID:            md.ID,
		Name:          md.Name,
		Description:   md.Description,
		Price:         md.Price,
		StockQuantity: md.StockQuantity,
		Display:       md.Display,
		CreatedBy:     md.CreatedBy,
		CreatedTime:   md.CreatedTime,
		UpdatedTime:   md.UpdatedTime,
	}
}

func NewProductResponses(mds []*models.ProductMD) []*ProductResponse {
	if len(mds) == 0 {
		return nil
	}

	res := make([]*ProductResponse, 0, len(mds))
	for _, md := range mds {
		if r := NewProductResponse(md); r != nil {
			res = append(res, r)
		}
	}
	return res
}
