/* !!
 * Code generated by fkit
 * If you need to write additional functions, should create a separate file.
 * File Created: Sunday, 27 April 2025 15:51:44 +07:00
 * Author: VietLD (leduyviet2612@gmail.com)
 * -----
 * Last Modified: Sunday, 27 April 2025 15:51:44 +07:00
 * Modified By: HIEUBV\hieubv
 * -----
 * Copyright 2025. All rights reserved.
 */

package cate_do

import (
	"github.com/bachhieu/fountain/baselib/v_log"
	"github.com/bachhieu/fountain/baselib/v_net/v_api"
	"github.com/bachhieu/fountain/proto/v_proto"
	"github.com/bachhieu/test/biz/dal/models"
)

// enable custom message validate if needed
// var _ validator.ICustomMessage = (*UpdateCateReq)(nil)

type UpdateCateReq struct {
	ID          string `json:"id" validate:"required,ulid" example:"01HFGRZQHPY8JHVRZ7NSRDGVB5"`
	Name        string `json:"name" validate:"omitempty,min=1,max=255" example:"Andreanne Zieme"`
	Description string `json:"description" validate:"omitempty,min=1,max=255" example:"blanditiis rerum illum maiores eveniet."`
	CreatedBy   string `json:"created_by" validate:"omitempty,min=1,max=255" example:"5oWUyVnW"`
}

func (d *UpdateCateReq) Validated() (*models.CateMD, *v_proto.VolioRpcError) {
	if err := v_api.Validate(d); err != nil {
		v_log.V(1).WithError(err).Errorf("UpdateCateReq::Validated - Error: %+v", err)
		return nil, v_proto.NewRpcError(int32(v_proto.VolioRpcErrorCodes_BAD_REQUEST), err.Error())
	}

	model := &models.CateMD{
		ID:          d.ID,
		Name:        d.Name,
		Description: d.Description,
		CreatedBy:   d.CreatedBy,
	}

	return model, nil
}
