/* !!
 * Code generated by fkit
 * If you need to write additional functions, should create a separate file.
 * File Created: Sunday, 27 April 2025 16:48:23 +07:00
 * Author: VietLD (leduyviet2612@gmail.com)
 * -----
 * Last Modified: Sunday, 27 April 2025 16:48:23 +07:00
 * Modified By: HIEUBV\hieubv
 * -----
 * Copyright 2025. All rights reserved.
 */

package reviews

import (
	"github.com/bachhieu/fountain/baselib/v_log"
	f_core "github.com/bachhieu/fountain/biz/f_core"
	"github.com/bachhieu/test/biz/dal/dao"
	"github.com/bachhieu/test/biz/dal/dao/postgres_dao"
	"github.com/bachhieu/test/biz/dal/dao/redis_dao"
)

type reviewDAO struct {
	reviewsDAO   *postgres_dao.ReviewsDAO
	reviewsCache *redis_dao.ReviewsCache
}

type ReviewsController struct {
	dao *reviewDAO
}

func (ctrl *ReviewsController) InstallController() {
	ctrl.dao.reviewsDAO = dao.GetReviewsDAO(dao.TEST_DB_MASTER)
	ctrl.dao.reviewsCache = dao.GetReviewsCache(dao.TEST_CACHE)
}

func (ctrl *ReviewsController) RegisterCallback(cb interface{}) {
}

func (ctrl *ReviewsController) AfterInstalledDone() {
	v_log.V(3).Infof("ReviewsController::AfterInstalledDone")
}

func init() {
	f_core.RegisterCoreController(&ReviewsController{dao: &reviewDAO{}})
}
