/* !!
 * Code generated by fkit
 * If you need to write additional functions, should create a separate file.
 * File Created: Sunday, 27 April 2025 16:48:23 +07:00
 * Author: VietLD (leduyviet2612@gmail.com)
 * -----
 * Last Modified: Sunday, 27 April 2025 16:48:23 +07:00
 * Modified By: HIEUBV\hieubv
 * -----
 * Copyright 2025. All rights reserved.
 */

package reviews

import (
	"github.com/bachhieu/fountain/baselib/v_log"
	"github.com/bachhieu/fountain/proto/v_proto"
	"github.com/bachhieu/test/biz/core"
	"github.com/bachhieu/test/biz/dal/do/review_do"
	"github.com/bachhieu/test/biz/dal/models"
)

var _ core.ReviewsCallback = &ReviewsController{}

func (ctrl *ReviewsController) Get(id string) *models.ReviewMD {
	// // Try get from cache first
	// if data := ctrl.dao.reviewsCache.Get(id); data != nil {
	// 	return data
	// }

	// Get from dao
	md := ctrl.dao.reviewsDAO.Get(id)
	if md == nil {
		return nil
	}

	// // Save to cache
	// go func() {
	// 	if err := ctrl.dao.reviewsCache.Save(md); err != nil {
	// 		v_log.V(1).WithError(err).Errorf("ReviewsController::Get - Cache Error: %+v", err)
	// 	}
	// }()

	return md
}

func (ctrl *ReviewsController) Gets(params *review_do.ReviewQueryParams, offset, limit int) ([]*models.ReviewMD, *v_proto.VolioRpcError) {
	res, err := ctrl.dao.reviewsDAO.Gets(params, offset, limit)
	if err != nil {
		v_log.V(1).WithError(err).Errorf("ReviewsController::Gets - Error: %+v", err)
		return nil, v_proto.NewRpcError(int32(v_proto.VolioRpcErrorCodes_BAD_REQUEST), "some thing went wrong")
	}

	return res, nil
}

func (ctrl *ReviewsController) CountTotal(params *review_do.ReviewQueryParams) int {
	return ctrl.dao.reviewsDAO.CountTotal(params)
}

func (ctrl *ReviewsController) Create(input *review_do.CreateReviewReq) *v_proto.VolioRpcError {
	md, err := input.Validated()
	if err != nil {
		v_log.V(1).WithError(err).Errorf("ReviewsController::Create - Error: %+v", err)
		return err
	}

	if err := ctrl.dao.reviewsDAO.Insert(md); err != nil {
		v_log.V(1).WithError(err).Errorf("ReviewsController::Create - Error: %+v", err)
		return v_proto.NewRpcError(int32(v_proto.VolioRpcErrorCodes_SAVE_DATA), "failed to create")
	}
	return nil
}

func (ctrl *ReviewsController) Update(input *review_do.UpdateReviewReq) *v_proto.VolioRpcError {
	newMd, err := input.Validated()
	if err != nil {
		v_log.V(1).WithError(err).Errorf("ReviewsController::Update - Error: %+v", err)
		return err
	}

	oldMd := ctrl.dao.reviewsDAO.Get(newMd.ID)
	if oldMd == nil {
		return v_proto.NewRpcError(int32(v_proto.VolioRpcErrorCodes_DATA_NOT_FOUND), "Review not found")
	}

	if err := ctrl.dao.reviewsDAO.Update(oldMd.AllowedUpdateFields(newMd)); err != nil {
		v_log.V(1).WithError(err).Errorf("ReviewsController::Update - Error: %+v", err)
		return v_proto.NewRpcError(int32(v_proto.VolioRpcErrorCodes_SAVE_DATA), "failed to update")
	}
	// Delete cache
	if err := ctrl.dao.reviewsCache.Delete(newMd.ID); err != nil {
		v_log.V(1).WithError(err).Errorf("ReviewsController::Update - Cache Error: %+v", err)
	}
	return nil
}

func (ctrl *ReviewsController) Delete(id string) *v_proto.VolioRpcError {
	// Delete from cache first
	if err := ctrl.dao.reviewsCache.Delete(id); err != nil {
		v_log.V(1).WithError(err).Errorf("ReviewsController::Delete - Cache Error: %+v", err)
	}

	if err := ctrl.dao.reviewsDAO.Delete(id); err != nil {
		v_log.V(1).WithError(err).Errorf("ReviewsController::Delete - Error: %+v", err)
		return v_proto.NewRpcError(int32(v_proto.VolioRpcErrorCodes_SAVE_DATA), "failed to delete")
	}
	return nil
}
