/* !!
 * Code generated by fkit
 * If you need to write additional functions, should create a separate file.
 * File Created: Sunday, 27 April 2025 16:10:50 +07:00
 * Author: VietLD (leduyviet2612@gmail.com)
 * -----
 * Last Modified: Sunday, 27 April 2025 16:10:50 +07:00
 * Modified By: HIEUBV\hieubv
 * -----
 * Copyright 2025. All rights reserved.
 */

package products

import (
	"github.com/bachhieu/fountain/baselib/v_net/v_api"
	"github.com/bachhieu/fountain/biz/f_core"
	"github.com/bachhieu/test/biz/core/products"
)

type ProductsAPI struct {
	*v_api.VolioAPI
	productsController *products.ProductsController
}

func NewProductsAPI(controllers []f_core.CoreController) *ProductsAPI {
	impl := &ProductsAPI{VolioAPI: v_api.GetVolioAPIInstance()}

	for _, ctrl := range controllers {
		switch x := ctrl.(type) {
		case *products.ProductsController:
			impl.productsController = x
		}
	}

	return impl
}
