/* !!
 * Code generated by fkit
 * If you need to write additional functions, should create a separate file.
 * File Created: Sunday, 27 April 2025 16:10:50 +07:00
 * Author: VietLD (leduyviet2612@gmail.com)
 * -----
 * Last Modified: Sunday, 27 April 2025 16:10:50 +07:00
 * Modified By: HIEUBV\hieubv
 * -----
 * Copyright 2025. All rights reserved.
 */

package products

import (
	"github.com/bachhieu/fountain/baselib/base"
	"github.com/bachhieu/fountain/baselib/v_log"
	"github.com/bachhieu/fountain/baselib/v_net/v_api"
	"github.com/bachhieu/fountain/proto/v_proto"
	"github.com/bachhieu/test/biz/dal/do/product_do"
	"github.com/gofiber/fiber/v2"
)

// @Summary      Get Pagination
// @Description  Get pagination of Product
// @Tags         Product
// @Accept       json
// @Produce      json
// @Param        Authorization  header    string  true  "Insert your access token" default(access_token)
// @Param        query_params              query     product_do.ProductQueryParams  false  "Query params"
// @Success      200          {object}  v_api.Response[[]product_do.ProductResponse]
// @Failure      400          {object}  v_proto.VolioRpcError
// @Failure      500          {object}  v_proto.VolioRpcError
// @Router       /admin/products/pagination [get]
func (api *ProductsAPI) GetPagination(ctx *fiber.Ctx) error {
	params := new(product_do.ProductQueryParams)
	if err := ctx.QueryParser(params); err != nil {
		v_log.V(1).WithError(err).Errorf("ProductsAPI::GetPagination - Parse params error: %+v", err)
		return v_api.WriteError(ctx, v_proto.NewRpcError(int32(v_proto.VolioRpcErrorCodes_BAD_REQUEST), "invalid parameters"))
	}

	offset, limit := v_api.GetQueryOffsetLimit(ctx)
	res, err := api.productsController.Gets(params, offset, limit)
	if err != nil {
		v_log.V(1).WithError(err).Errorf("ProductsAPI::GetPagination - Error: %+v", err)
		return v_api.WriteError(ctx, err)
	}

	total := api.productsController.CountTotal(params)

	v_log.V(3).Infof("ProductsAPI::GetPagination - Reply: %s", base.JSONDebugDataString(res))

	return v_api.WithContext(ctx).WithPaginationByLoadMore(total, offset, limit).WriteSuccess(product_do.NewProductResponses(res))
}
