/* !!
 * Code generated by fkit
 * If you need to write additional functions, should create a separate file.
 * File Created: Sunday, 27 April 2025 15:51:44 +07:00
 * Author: VietLD (leduyviet2612@gmail.com)
 * -----
 * Last Modified: Sunday, 27 April 2025 15:51:44 +07:00
 * Modified By: HIEUBV\hieubv
 * -----
 * Copyright 2025. All rights reserved.
 */

package cates

import (
	"github.com/bachhieu/fountain/baselib/v_net/v_api"
	"github.com/bachhieu/fountain/biz/f_core"
	"github.com/bachhieu/test/biz/core/cates"
)

type CatesAPI struct {
	*v_api.VolioAPI
	catesController *cates.CatesController
}

func NewCatesAPI(controllers []f_core.CoreController) *CatesAPI {
	impl := &CatesAPI{VolioAPI: v_api.GetVolioAPIInstance()}

	for _, ctrl := range controllers {
		switch x := ctrl.(type) {
		case *cates.CatesController:
			impl.catesController = x
		}
	}

	return impl
}
