/* !!
 * Code generated by fkit
 * If you need to write additional functions, should create a separate file.
 * File Created: Sunday, 27 April 2025 15:51:44 +07:00
 * Author: VietLD (leduyviet2612@gmail.com)
 * -----
 * Last Modified: Sunday, 27 April 2025 15:51:44 +07:00
 * Modified By: HIEUBV\hieubv
 * -----
 * Copyright 2025. All rights reserved.
 */

package redis_dao

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/bachhieu/fountain/baselib/base"
	"github.com/bachhieu/fountain/baselib/redis_client"
	"github.com/bachhieu/fountain/baselib/v_log"
	"github.com/bachhieu/test/biz/dal/models"
)

const (
	KCatesDataFormat = "fountain:cates:%s" // id
)

func createCatesDataKey(id string) string {
	return fmt.Sprintf(KCatesDataFormat, id)
}

var CatesCacheInstance *CatesCache

type CatesCache struct {
	client *redis_client.Pool
}

func NewCatesCache(client *redis_client.Pool) *CatesCache {
	if CatesCacheInstance == nil {
		CatesCacheInstance = &CatesCache{client}
	}
	return CatesCacheInstance
}
func (dao *CatesCache) Save(mds ...*models.CateMD) error {
	ctx, cancel := redis_client.CreateDefaultCtx()
	defer cancel()

	conn := dao.client.Get()
	if conn == nil {
		err := fmt.Errorf("can not create connection")
		v_log.V(1).WithError(err).Errorf("CatesCache::SaveCates - Error: %+v", err)
		return err
	}

	pipeline := conn.Pipeline()
	for _, md := range mds {
		pipeline.Set(ctx, createCatesDataKey(md.ID), base.JSONDebugDataString(md), 24*time.Hour)
	}

	if _, err := pipeline.Exec(ctx); err != nil {
		v_log.V(1).WithError(err).Errorf("CatesCache::SaveCates - Error: %+v", err)
		return err
	}

	return nil
}

func (dao *CatesCache) Get(id string) *models.CateMD {
	key := createCatesDataKey(id)

	ctx, cancel := redis_client.CreateDefaultCtx()
	defer cancel()

	conn := dao.client.Get()
	if conn == nil {
		err := fmt.Errorf("cannot create connection")
		v_log.V(1).WithError(err).Errorf("CatesCache::GetCates - Error: %+v", err)
		return nil
	}

	dataJSON := conn.Get(ctx, key).Val()
	if dataJSON != "" {
		var res models.CateMD
		if err := json.Unmarshal([]byte(dataJSON), &res); err != nil {
			v_log.V(1).WithError(err).Errorf("CatesCache::GetCates - Redis unmarshal error: %+v", err)
			return nil
		}
		return &res
	}

	return nil
}

func (dao *CatesCache) Delete(id string) error {
	key := createCatesDataKey(id)

	ctx, cancel := redis_client.CreateDefaultCtx()
	defer cancel()

	conn := dao.client.Get()
	if conn == nil {
		err := fmt.Errorf("can not create connection")
		v_log.V(1).WithError(err).Errorf("CatesCache::DeleteCates - Error: %+v", err)
		return err
	}

	return conn.Del(ctx, key).Err()
}
