/* !!
 * Code generated by fkit
 * If you need to write additional functions, should create a separate file.
 * File Created: Sunday, 27 April 2025 16:10:50 +07:00
 * Author: VietLD (leduyviet2612@gmail.com)
 * -----
 * Last Modified: Sunday, 27 April 2025 16:10:50 +07:00
 * Modified By: HIEUBV\hieubv
 * -----
 * Copyright 2025. All rights reserved.
 */

package redis_dao

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/bachhieu/fountain/baselib/base"
	"github.com/bachhieu/fountain/baselib/redis_client"
	"github.com/bachhieu/fountain/baselib/v_log"
	"github.com/bachhieu/test/biz/dal/models"
)

const (
	KProductsDataFormat = "fountain:products:%s" // id
)

func createProductsDataKey(id string) string {
	return fmt.Sprintf(KProductsDataFormat, id)
}

var ProductsCacheInstance *ProductsCache

type ProductsCache struct {
	client *redis_client.Pool
}

func NewProductsCache(client *redis_client.Pool) *ProductsCache {
	if ProductsCacheInstance == nil {
		ProductsCacheInstance = &ProductsCache{client}
	}
	return ProductsCacheInstance
}
func (dao *ProductsCache) Save(mds ...*models.ProductMD) error {
	ctx, cancel := redis_client.CreateDefaultCtx()
	defer cancel()

	conn := dao.client.Get()
	if conn == nil {
		err := fmt.Errorf("can not create connection")
		v_log.V(1).WithError(err).Errorf("ProductsCache::SaveProducts - Error: %+v", err)
		return err
	}

	pipeline := conn.Pipeline()
	for _, md := range mds {
		pipeline.Set(ctx, createProductsDataKey(md.ID), base.JSONDebugDataString(md), 24*time.Hour)
	}

	if _, err := pipeline.Exec(ctx); err != nil {
		v_log.V(1).WithError(err).Errorf("ProductsCache::SaveProducts - Error: %+v", err)
		return err
	}

	return nil
}

func (dao *ProductsCache) Get(id string) *models.ProductMD {
	key := createProductsDataKey(id)

	ctx, cancel := redis_client.CreateDefaultCtx()
	defer cancel()

	conn := dao.client.Get()
	if conn == nil {
		err := fmt.Errorf("cannot create connection")
		v_log.V(1).WithError(err).Errorf("ProductsCache::GetProducts - Error: %+v", err)
		return nil
	}

	dataJSON := conn.Get(ctx, key).Val()
	if dataJSON != "" {
		var res models.ProductMD
		if err := json.Unmarshal([]byte(dataJSON), &res); err != nil {
			v_log.V(1).WithError(err).Errorf("ProductsCache::GetProducts - Redis unmarshal error: %+v", err)
			return nil
		}
		return &res
	}

	return nil
}

func (dao *ProductsCache) Delete(id string) error {
	key := createProductsDataKey(id)

	ctx, cancel := redis_client.CreateDefaultCtx()
	defer cancel()

	conn := dao.client.Get()
	if conn == nil {
		err := fmt.Errorf("can not create connection")
		v_log.V(1).WithError(err).Errorf("ProductsCache::DeleteProducts - Error: %+v", err)
		return err
	}

	return conn.Del(ctx, key).Err()
}
