/* !!
 * Code generated by fkit
 * If you need to write additional functions, should create a separate file.
 * File Created: Sunday, 27 April 2025 16:48:23 +07:00
 * Author: VietLD (leduyviet2612@gmail.com)
 * -----
 * Last Modified: Sunday, 27 April 2025 16:48:23 +07:00
 * Modified By: HIEUBV\hieubv
 * -----
 * Copyright 2025. All rights reserved.
 */

package redis_dao

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/bachhieu/fountain/baselib/base"
	"github.com/bachhieu/fountain/baselib/redis_client"
	"github.com/bachhieu/fountain/baselib/v_log"
	"github.com/bachhieu/test/biz/dal/models"
)

const (
	KReviewsDataFormat = "fountain:reviews:%s" // id
)

func createReviewsDataKey(id string) string {
	return fmt.Sprintf(KReviewsDataFormat, id)
}

var ReviewsCacheInstance *ReviewsCache

type ReviewsCache struct {
	client *redis_client.Pool
}

func NewReviewsCache(client *redis_client.Pool) *ReviewsCache {
	if ReviewsCacheInstance == nil {
		ReviewsCacheInstance = &ReviewsCache{client}
	}
	return ReviewsCacheInstance
}
func (dao *ReviewsCache) Save(mds ...*models.ReviewMD) error {
	ctx, cancel := redis_client.CreateDefaultCtx()
	defer cancel()

	conn := dao.client.Get()
	if conn == nil {
		err := fmt.Errorf("can not create connection")
		v_log.V(1).WithError(err).Errorf("ReviewsCache::SaveReviews - Error: %+v", err)
		return err
	}

	pipeline := conn.Pipeline()
	for _, md := range mds {
		pipeline.Set(ctx, createReviewsDataKey(md.ID), base.JSONDebugDataString(md), 24*time.Hour)
	}

	if _, err := pipeline.Exec(ctx); err != nil {
		v_log.V(1).WithError(err).Errorf("ReviewsCache::SaveReviews - Error: %+v", err)
		return err
	}

	return nil
}

func (dao *ReviewsCache) Get(id string) *models.ReviewMD {
	key := createReviewsDataKey(id)

	ctx, cancel := redis_client.CreateDefaultCtx()
	defer cancel()

	conn := dao.client.Get()
	if conn == nil {
		err := fmt.Errorf("cannot create connection")
		v_log.V(1).WithError(err).Errorf("ReviewsCache::GetReviews - Error: %+v", err)
		return nil
	}

	dataJSON := conn.Get(ctx, key).Val()
	if dataJSON != "" {
		var res models.ReviewMD
		if err := json.Unmarshal([]byte(dataJSON), &res); err != nil {
			v_log.V(1).WithError(err).Errorf("ReviewsCache::GetReviews - Redis unmarshal error: %+v", err)
			return nil
		}
		return &res
	}

	return nil
}

func (dao *ReviewsCache) Delete(id string) error {
	key := createReviewsDataKey(id)

	ctx, cancel := redis_client.CreateDefaultCtx()
	defer cancel()

	conn := dao.client.Get()
	if conn == nil {
		err := fmt.Errorf("can not create connection")
		v_log.V(1).WithError(err).Errorf("ReviewsCache::DeleteReviews - Error: %+v", err)
		return err
	}

	return conn.Del(ctx, key).Err()
}
