/* !!
 * Code generated by fkit
 * If you need to write additional functions, should create a separate file.
 * File Created: Sunday, 27 April 2025 16:48:24 +07:00
 * Author: VietLD (leduyviet2612@gmail.com)
 * -----
 * Last Modified: Sunday, 27 April 2025 16:48:24 +07:00
 * Modified By: HIEUBV\hieubv
 * -----
 * Copyright 2025. All rights reserved.
 */

package review_do

import (
	"crypto/rand"
	"time"

	"github.com/bachhieu/fountain/baselib/v_log"
	"github.com/bachhieu/fountain/baselib/v_net/v_api"
	"github.com/bachhieu/fountain/proto/v_proto"
	"github.com/bachhieu/test/biz/dal/models"
	"github.com/oklog/ulid/v2"
)

// enable custom message validate if needed
// var _ validator.ICustomMessage = (*CreateReviewReq)(nil)

type CreateReviewReq struct {
	ProductID string `json:"product_id" validate:"omitempty,min=1,max=255" example:"01JSVA6TGG5PNH8Q51351FSY12"`
	Rating    int    `json:"rating" validate:"omitempty,min=1,max=5" example:"5"`
	Comment   string `json:"comment" validate:"omitempty,min=1,max=255" example:"BqlFnqkM"`
	UserID    string `json:"-"`
}

func (d *CreateReviewReq) Validated() (*models.ReviewMD, *v_proto.VolioRpcError) {
	if err := v_api.Validate(d); err != nil {
		v_log.V(1).WithError(err).Errorf("CreateReviewReq::Validated - Error: %+v", err)
		return nil, v_proto.NewRpcError(int32(v_proto.VolioRpcErrorCodes_BAD_REQUEST), err.Error())
	}

	timeNow := int32(time.Now().Unix())

	model := &models.ReviewMD{
		ID:          ulid.MustNew(ulid.Now(), rand.Reader).String(),
		ProductID:   d.ProductID,
		UserID:      d.UserID,
		Rating:      d.Rating,
		Comment:     d.Comment,
		CreatedTime: timeNow,
		UpdatedTime: timeNow,
	}

	return model, nil
}
