/* !!
 * Code generated by fkit
 * If you need to write additional functions, should create a separate file.
 * File Created: Sunday, 27 April 2025 16:48:24 +07:00
 * Author: VietLD (leduyviet2612@gmail.com)
 * -----
 * Last Modified: Sunday, 27 April 2025 16:48:24 +07:00
 * Modified By: HIEUBV\hieubv
 * -----
 * Copyright 2025. All rights reserved.
 */

package review_do

import (
	"github.com/bachhieu/test/biz/dal/models"
)

type ReviewResponse struct {
	ID          string `json:"id" example:"01HFGRZQHPY8JHVRZ7NSRDGVB5"`
	ProductID   string `json:"product_id" example:"gPdBjIkf"`
	UserID      string `json:"user_id" example:"gPdBjIkf"`
	Rating      int    `json:"rating" example:"5"`
	Comment     string `json:"comment" example:"BqlFnqkM"`
	CreatedTime int32  `json:"created_time" example:"1710008982"`
	UpdatedTime int32  `json:"updated_time" example:"1710008982"`
}

func NewReviewResponse(md *models.ReviewMD) *ReviewResponse {
	if md == nil {
		return nil
	}

	return &ReviewResponse{
		ID:          md.ID,
		ProductID:   md.ProductID,
		UserID:      md.UserID,
		Rating:      md.Rating,
		Comment:     md.Comment,
		CreatedTime: md.CreatedTime,
		UpdatedTime: md.UpdatedTime,
	}
}

func NewReviewResponses(mds []*models.ReviewMD) []*ReviewResponse {
	if len(mds) == 0 {
		return nil
	}

	res := make([]*ReviewResponse, 0, len(mds))
	for _, md := range mds {
		if r := NewReviewResponse(md); r != nil {
			res = append(res, r)
		}
	}
	return res
}
