/* !!
 * Code generated by fkit
 * If you need to write additional functions, should create a separate file.
 * File Created: Sunday, 27 April 2025 16:48:24 +07:00
 * Author: VietLD (leduyviet2612@gmail.com)
 * -----
 * Last Modified: Sunday, 27 April 2025 16:48:24 +07:00
 * Modified By: HIEUBV\hieubv
 * -----
 * Copyright 2025. All rights reserved.
 */

package review_do

import (
	"github.com/bachhieu/fountain/baselib/v_log"
	"github.com/bachhieu/fountain/baselib/v_net/v_api"
	"github.com/bachhieu/fountain/proto/v_proto"
	"github.com/bachhieu/test/biz/dal/models"
)

// enable custom message validate if needed
// var _ validator.ICustomMessage = (*UpdateReviewReq)(nil)

type UpdateReviewReq struct {
	ID        string `json:"id" validate:"required,ulid" example:"01HFGRZQHPY8JHVRZ7NSRDGVB5"`
	ProductID string `json:"product_id" validate:"omitempty,min=1,max=255" example:"gPdBjIkf"`
	UserID    string `json:"user_id" validate:"omitempty,min=1,max=255" example:"gPdBjIkf"`
	Rating    int    `json:"rating" validate:"omitempty,min=1,max=255" example:"5"`
	Comment   string `json:"comment" validate:"omitempty,min=1,max=255" example:"BqlFnqkM"`
}

func (d *UpdateReviewReq) Validated() (*models.ReviewMD, *v_proto.VolioRpcError) {
	if err := v_api.Validate(d); err != nil {
		v_log.V(1).WithError(err).Errorf("UpdateReviewReq::Validated - Error: %+v", err)
		return nil, v_proto.NewRpcError(int32(v_proto.VolioRpcErrorCodes_BAD_REQUEST), err.Error())
	}

	model := &models.ReviewMD{
		ID:        d.ID,
		ProductID: d.ProductID,
		UserID:    d.UserID,
		Rating:    d.Rating,
		Comment:   d.Comment,
	}

	return model, nil
}
